[package]
name = "constellation-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "constellation"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
chrono.workspace = true
constellation-core = { version = "0.1.0-alpha.1", path = "../../crates/constellation-core" }
constellation-identity = { version = "0.1.0-alpha.1", path = "../../crates/constellation-identity" }
constellation-plugins = { version = "0.1.0-alpha.1", path = "../../crates/constellation-plugins" }
constellation-secrets = { version = "0.1.0-alpha.1", path = "../../crates/constellation-secrets" }
constellation-teams = { version = "0.1.0-alpha.1", path = "../../crates/constellation-teams" }
constellation-workflows = { version = "0.1.0-alpha.1", path = "../../crates/constellation-workflows" }
futures-util.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sysinfo.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
