[package]
name = "constellation-identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
data-encoding.workspace = true
ed25519-dalek.workspace = true
hmac.workspace = true
rand_core.workspace = true
rcgen.workspace = true
serde.workspace = true
sha2.workspace = true
spake2.workspace = true
subtle.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
